In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("emails.csv")

In [3]:
data

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [7]:
#eliminating 1st and last column and storing in x 
x=data.iloc[:,1:3001]

In [8]:
x

,the,to,ect,and,for,of,a,you,hou,in,...,enhancements,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry
0,0,0,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
4,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,2,2,2,3,0,0,32,0,0,5,...,0,0,0,0,0,0,0,0,0,0
5168,35,27,11,2,6,5,151,4,3,23,...,0,0,0,0,0,0,0,0,1,0
5169,0,0,1,1,0,0,11,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5170,2,7,1,0,2,1,28,2,0,8,...,0,0,0,0,0,0,0,0,1,0
5171,22,24,5,1,6,5,148,8,2,23,...,0,0,0,0,0,0,0,0,0,0

In [9]:
y=data.iloc[:,-1]
y

0       0
1       0
2       0
3       0
4       0
       ..
5167    0
5168    0
5169    1
5170    1
5171    0
Name: Prediction, Length: 5172, dtype: int64

# Code for KNN

In [21]:
import sklearn

In [13]:
#splitting the dataset into 80% training data and 20% testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [16]:
#data preprocessing
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [18]:
#fitting knn algo to training data
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=7)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [19]:
#predicting test result
y_pred=classifier.predict(x_test)

In [28]:
#evaluation  of result using confusion matrix
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
#f1 score is harmonic mean of precision and recall and is
#better measure than accuracy

              precision    recall  f1-score   support

           0       0.98      0.75      0.85       747
           1       0.59      0.96      0.73       288

    accuracy                           0.80      1035
   macro avg       0.79      0.85      0.79      1035
weighted avg       0.87      0.80      0.81      1035

[[557 190]
 [ 12 276]]

# Code for SVM

In [23]:
from sklearn.svm import SVC

In [29]:
#data preprocessing
#step 1: dividing data into attributes and labels
df=data.copy()

In [30]:
df.dropna(inplace=True)

In [36]:

X=df.drop(['Prediction'],axis=1)
Y=df['Prediction']

In [37]:
#step 2:splitting into training and testing data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [38]:
#training the SVM algorithm
svcclassifier=SVC(kernel='linear')
svcclassifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [39]:
#making predictions
Y_pred=svcclassifier.predict(X_test)
print(Y_pred)

[1 0 0 ... 0 0 1]

In [42]:
#evaluatung result of svm
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       708
           1       0.94      0.94      0.94       327

    accuracy                           0.96      1035
   macro avg       0.96      0.96      0.96      1035
weighted avg       0.96      0.96      0.96      1035

[[689  19]
 [ 19 308]]